# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Snowdj Documents
tagline:          A wiki style webpage
url:              http://snowdj.github.io/
paginate:         1

baseurl:          http://snowdj.github.io/

author:
  name:           snowdj
  url:            https://twitter.com/snowdj
  email:          snowdj@gmail.com






# Custom vars
version:          1.0.0
github:
  repo:           http://snowdj.github.io/

# This is the list of pages to incldue in the header of the website.
pages_list: {'About':'/about','Archive':'/archive','Feed':'/atom.xml'}
